services:
  - type: worker
    name: nse-option-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python bt5.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
